// Playlists precargadas. Cada canción = [título, artista, idYouTube].
export const GENRES = [
  { id:"rock", name:"Rock Nacional 🇦🇷", em:"🎸", songs:[
    ["De música ligera","Soda Stereo","T_FkEw27XJ0"],
    ["Persiana americana","Soda Stereo","LalPz4lIZYk"],
    ["En la ciudad de la furia","Soda Stereo","vo7jBHB66q4"],
    ["Cuando pase el temblor","Soda Stereo","7PHqjNbwnwU"],
    ["Crimen","Gustavo Cerati","YVXNPPdh6wE"],
    ["Seminare","Serú Girán","xVdtGR_zgdA"],
    ["El amor después del amor","Fito Páez","knvgOdKPaMQ"],
    ["Mariposa Technicolor","Fito Páez","CRBincBc_8k"],
    ["Los dinosaurios","Charly García","BAuqozi64WQ"],
    ["Rasguña las piedras","Sui Generis","DrKRNJGAyHw"],
    ["Matador","Los Fabulosos Cadillacs","dKJM2ux3bF8"],
    ["Ji Ji Ji","Los Redondos","CnJqYsSOgfg"],
    ["Flaca","Andrés Calamaro","UCF9oHXhDMU"],
    ["Yo vengo a ofrecer mi corazón","Fito Páez","cg1FigbX6BM"],
    ["Zona de promesas","Soda Stereo","QLmTwB3AtNM"],
    ["Un vestido y un amor","Fito Páez","7aSsSf-e4zQ"],
    ["Prófugos","Soda Stereo","lGptyREttJ4"],
    ["Trátame suavemente","Soda Stereo","UPVfQKUHTSc"],
    ["Nada personal","Soda Stereo","ko24BZXdK8c"],
    ["Demoliendo hoteles","Charly García","Mm3IgrVsu24"],
    ["No voy en tren","Charly García","P3L10KNMptw"],
    ["Muchacha (ojos de papel)","Almendra","33bSMJF-SfE"],
    ["La balsa","Los Gatos","_I9aI8ejnqY"],
    ["Cactus","Gustavo Cerati","a7_al3uciVc"],
    ["La argentinidad al palo","Bersuit Vergarabat","972s6-BLGtQ"],
    ["Se viene","Bersuit Vergarabat","ACRVZzKu5h0"],
    ["Loco (tu forma de ser)","Los Auténticos Decadentes","fgXDHQm5eq4"],
    ["La rubia tarada","Sumo","T-JcurmwZpQ"],
    ["Mal bicho","Los Fabulosos Cadillacs","9xua8KKPZME"],
    ["Desarma y sangra","Fito Páez","tPW3K_Kn_Aw"],
    ["Canción de Alicia en el país","Serú Girán","YRNFye2SysM"],
    ["Inconsciente colectivo","Charly García","SNZ6Qd58ixI"],
    ["Mañana en el Abasto","Sumo","Z644FsmcqWU"],
    ["Cuando seas grande","Miguel Mateos","yRalw2pRKYA"],
    ["¿Qué ves?","Divididos","DtOmy2pC_7g"],
    ["Presente (El momento en que estás)","Vox Dei","W4a0I9-cdt0"],
  ]},
  { id:"cumbia", name:"Cumbia y Cuarteto 🇦🇷", em:"🪗", songs:[
    ["Soy cordobés","Rodrigo","EZaO0mgpy6I"],
    ["La mano de Dios","Rodrigo","EAk-l1VHzBw"],
    ["Ocho cuarenta","Rodrigo","pcoRGLd79Nw"],
    ["Quién se ha tomado todo el vino","La Mona Jiménez","YjIhq5dJKQA"],
    ["No me arrepiento de este amor","Gilda","8iUkmnLc1ec"],
    ["Fuiste","Gilda","mm_SwD5PYvY"],
    ["Corazón valiente","Gilda","yykYZhD4Wwc"],
    ["No te creas tan importante","Damas Gratis","j6CUfl4aX9s"],
    ["El bombón asesino","Los Palmeras","UeFC_9oGqWg"],
    ["La pollera amarilla","Los Palmeras","W9sQmwS6c4Q"],
    ["La ventanita","Grupo Sombras","Ykt2edUBEyA"],
    ["Beso a beso","La Mona Jiménez","Xv2vXP7R-KI"],
    ["Amor clasificado","Rodrigo","Wp75WKhWT48"],
    ["Cómo olvidarla","Rodrigo","59n6vkmpazE"],
    ["Laura, se te ve la tanga","Damas Gratis","jKgCg4cAVcw"],
    ["Se me ha perdido el corazón","Gilda","X72XPwSKcJ4"],
    ["Paisaje","Gilda","e-uNMZ1wfR4"],
    ["No es mi despedida","Gilda","y4Rtfp0Nx4k"],
    ["La Suavecita","Los Palmeras ft. Soledad","wA6S57yVqA8"],
    ["Nunca me faltes","Antonio Ríos","Du1UJyRwmts"],
    ["Hazme entender","Ráfaga","kDxp-aeJ0sw"],
    ["Mentirosa","Ráfaga","ihrUZRxgef4"],
    ["La Vecina","Amar Azul","wk-nCzxthAo"],
    ["Perdiste","Ulises Bueno","zxgMngLW65E"],
    ["Nunca es suficiente","Los Ángeles Azules","rJAZtuQqerE"],
    ["Cómo te voy a olvidar","Los Ángeles Azules","nxXvOEPsE0s"],
    ["El Listón de tu Pelo","Los Ángeles Azules","_bgfySYD544"],
    ["Eres la Persona Correcta en el Momento Equivocado","La Konga ft. Chipote","Jb1VL3b7K0Y"],
    ["Corazón Mentiroso","Karina \"La Princesita\"","yGFgbsKtcoQ"],
    ["El Arroyo","Los Pibes Chorros","2wafC110dRI"],
    ["La Cumbia de los Trapos","Yerba Brava","MUUrW7xJSw4"],
    ["Vete","Ráfaga","fV7GEqbC5r0"],
    ["El Africano","Wilfrido Vargas","H76FWhBc87o"],
    ["Con el Corazón en la Mano","Antonio Ríos","Hjm91Yfbsuk"],
  ]},
  { id:"pop", name:"Pop Latino / Reggaetón", em:"🔥", songs:[
    ["Despacito","Luis Fonsi ft. Daddy Yankee","FXovf5dsRTw"],
    ["Gasolina","Daddy Yankee","2djj_KnGwjk"],
    ["Vivir mi vida","Marc Anthony","79OxD7KNlYw"],
    ["Bailando","Enrique Iglesias","NUsoVlDFqZg"],
    ["La camisa negra","Juanes","7fwUH0oRmkQ"],
    ["Tusa","Karol G ft. Nicki Minaj","tbneQDc2H3I"],
    ["Hawái","Maluma","n_2ZYU72BYQ"],
    ["Con altura","Rosalía y J Balvin","p7bfOZek9t4"],
    ["La tortura","Shakira ft. Alejandro Sanz","Dsp_8Lm1eSk"],
    ["Hips Don't Lie","Shakira","DUT5rEU6pqM"],
    ["Livin' la Vida Loca","Ricky Martin","p47fEXGabaY"],
    ["Vente Pa' Ca","Ricky Martin ft. Maluma","COJp2Ejz0x0"],
    ["Propuesta indecente","Romeo Santos","wJYy7Yuf1Ig"],
    ["Obsesión","Aventura","8_QY5gFQUTg"],
    ["Felices los 4","Maluma","9rp10tWxZnk"],
    ["Chantaje","Shakira ft. Maluma","6Mgqbai3fKo"],
    ["El perdón","Nicky Jam & Enrique Iglesias","zs6aDvOTlMo"],
    ["Hasta el amanecer","Nicky Jam","LKf8GodiVtU"],
    ["Mi Gente","J Balvin","wnJ6LuUFpMo"],
    ["Ginza","J Balvin","T2eguXvbV7s"],
    ["Ay vamos","J Balvin","6B76JriqgSY"],
    ["China","Anuel, Daddy Yankee, Karol G, Ozuna, J Balvin","0VR3dfZf9Yg"],
    ["Baila Baila Baila","Ozuna","ucbQmTVZKUI"],
    ["Taki Taki","DJ Snake, Ozuna, Cardi B, Selena","ITHYU-YfsqA"],
    ["Corazón","Maluma ft. Nego do Borel","hFjCphQtaZM"],
    ["Reggaetón Lento","CNCO","7jpqqBX-Myw"],
    ["Súbeme la radio","Enrique Iglesias","0UXjeGUizJE"],
    ["Waka Waka (Esto Es África)","Shakira ft. Freshlyground","Ntn1-SocNiY"],
    ["Ay, DIOS Mío!","Karol G","f1UAcIGcer8"],
    ["Mayores","Becky G ft. Bad Bunny","GMFewiplIbw"],
    ["Se Preparó","Ozuna","JbVP_aZiFSY"],
    ["Follow The Leader","Wisin & Yandel ft. Jennifer Lopez","-OviNhgWa4g"],
    ["Échame La Culpa","Luis Fonsi ft. Demi Lovato","YDswuo2dIvY"],
    ["Pepas","Farruko","y8trd3gjJt0"],
    ["La Bachata","Manuel Turizo","sBLM_LzfCz4"],
  ]},
  { id:"inter", name:"Rock & Pop Internacional 🌎", em:"🌎", songs:[
    ["Bohemian Rhapsody","Queen","fJ9rUzIMcZQ"],
    ["Don't Stop Me Now","Queen","HgzGwKwLmgM"],
    ["Sweet Child O' Mine","Guns N' Roses","oMfMUfgjiLg"],
    ["Wonderwall","Oasis","rj5wZqReXQE"],
    ["Billie Jean","Michael Jackson","Zi_XLOBDo_Y"],
    ["Someone Like You","Adele","hLQl3WQQoQ0"],
    ["Shape of You","Ed Sheeran","xTvyyoF_LZY"],
    ["Yellow","Coldplay","yKNxeF4KMsY"],
    ["Zombie","The Cranberries","6Ejga4kJUts"],
    ["Smells Like Teen Spirit","Nirvana","hTWKbfoikeg"],
    ["Livin' on a Prayer","Bon Jovi","lDK9QqIzhwk"],
    ["I Want It That Way","Backstreet Boys","4fndeDfaWCg"],
    ["Africa","Toto","FTQbiNvZqaY"],
    ["Believer","Imagine Dragons","Kx7B-XvmFtE"],
    ["Rolling in the Deep","Adele","rYEDA3JcQqw"],
    ["We Will Rock You","Queen","-tJYN-eG1zk"],
    ["We Are the Champions","Queen","04854XqcfCY"],
    ["Hey Jude","The Beatles","mQER0A0ej0M"],
    ["Let It Be","The Beatles","CGj85pVzRJs"],
    ["Imagine","John Lennon","rAn-AWXtHv0"],
    ["Hotel California","Eagles","dLl4PZtxia8"],
    ["Every Breath You Take","The Police","OMOGaugKpzs"],
    ["Losing My Religion","R.E.M.","Efa6BAWPm9o"],
    ["With or Without You","U2","ujNeHIo7oTE"],
    ["Nothing Else Matters","Metallica","tAGnKpE4NCI"],
    ["Highway to Hell","AC/DC","l482T0yNkeo"],
    ["Thunderstruck","AC/DC","v2AC41dglnM"],
    ["Creep","Radiohead","XFkzRNyygfk"],
    ["Numb","Linkin Park","kXYiU_JCYtU"],
    ["Fix You","Coldplay","k4V3Mo61fJM"],
    ["Perfect","Ed Sheeran","ORrFJ63nlcA"],
    ["Sugar","Maroon 5","MozAXGgC1Mc"],
    ["Thriller","Michael Jackson","Z85lxckrtzg"],
    ["Come Together","The Beatles","45cYwDMibGo"],
    ["November Rain","Guns N' Roses","y6lfK3bH4z8"],
    ["Come As You Are","Nirvana","vabnZ9-ex7o"],
    ["Somebody to Love","Queen","kijpcUv-b8M"],
  ]},
  { id:"clasicos", name:"Clásicos 80s / 90s", em:"📼", songs:[
    ["Color esperanza","Diego Torres","0SgzUWa7EeQ"],
    ["Corazón espinado","Maná ft. Santana","t6omUxqhG78"],
    ["Rayando el sol","Maná","8lbsQyMhMT8"],
    ["Oye mi amor","Maná","iuiepR7HkM4"],
    ["La incondicional","Luis Miguel","wOjzo02Tmck"],
    ["Ahora te puedes marchar","Luis Miguel","yG7MPEQm1-w"],
    ["La bilirrubina","Juan Luis Guerra","K8PpV3yK5iA"],
    ["A Dios le pido","Juanes","kMIaYXxLnUA"],
    ["Entra en mi vida","Sin Bandera","8ZjCaxt565s"],
    ["A puro dolor","Son by Four","kAKVT1HWNsg"],
    ["Vivo por ella","Andrea Bocelli & Marta Sánchez","2gTfde2npkM"],
    ["Bachata rosa","Juan Luis Guerra","WfMO_AETgB0"],
    ["Burbujas de amor","Juan Luis Guerra","v0ckuv1xBm0"],
    ["Ojalá que llueva café","Juan Luis Guerra","suQC8d-YkeU"],
    ["La flaca","Jarabe de Palo","r2g0pM3PMNQ"],
    ["Corazón partío","Alejandro Sanz","mE4Mik_vfJA"],
    ["Amiga mía","Alejandro Sanz","44Qh0p9xE6o"],
    ["Mujer contra mujer","Mecano","wVSA2CEIQ7U"],
    ["Hijo de la luna","Mecano","OwGG5fX7bxY"],
    ["Me cuesta tanto olvidarte","Mecano","8f2Vyb014D0"],
    ["La chica de ayer","Nacha Pop","oAcwJlNdwso"],
    ["Eres tú","Mocedades","A5vaIjBQnmk"],
    ["Un beso y una flor","Nino Bravo","2gsmZ-UZAA4"],
    ["Bidi Bidi Bom Bom","Selena","RKGbjJarMeA"],
    ["Amor prohibido","Selena","dvfZ95ueOcQ"],
    ["Historia de Taxi","Ricardo Arjona","-apU2sviHCM"],
    ["Mujeres","Ricardo Arjona","ucyQM5z2qHQ"],
    ["Un Millón de Amigos","Roberto Carlos","7XRmbPJJTSY"],
    ["Te Amo","Franco De Vita","hNDtsPMX7p0"],
    ["Tiempo de Vals","Chayanne","wHIKeI6jpuk"],
    ["Simplemente Amigos","Ana Gabriel","kF5dQugED-M"],
    ["Toda la Vida","Emmanuel","HaC4JUi9w2c"],
    ["Amante Bandido","Miguel Bosé","Cwc9HjtGrg8"],
  ]},
  { id:"disney", name:"Disney y Películas", em:"🏰", songs:[
    ["Un mundo ideal","Aladdín","QCli1WXapIY"],
    ["Libre soy","Frozen","rVjI9YRc4pE"],
    ["Recuérdame","Coco","rSWj__OmHis"],
    ["Un poco loco","Coco","yZ7cBunq8xo"],
    ["Bajo el mar","La Sirenita","DDSerADikPg"],
    ["My Heart Will Go On","Titanic","9bFHsd3o1w0"],
    ["Colores en el viento","Pocahontas","Tf42lskNSqs"],
    ["Hakuna Matata","El Rey León","U-fR1JUS450"],
    ["Mi reflejo","Mulán","j__gnuV-7lI"],
    ["Cuando empezaré a vivir","Enredados","NjkAgGwXaSs"],
    ["Bella y Bestia son","La Bella y la Bestia","kY7mwb3EhbM"],
    ["El ciclo sin fin","El Rey León","5qYjzNv-WoA"],
    ["Yo quisiera ya ser el rey","El Rey León","L_mLtGKRG9Q"],
    ["Veo en ti la luz","Enredados","fZSZMp32XaA"],
    ["No hablaré de mi amor","Hércules","uJcl-pnTB7A"],
    ["Voy a hacer todo un hombre de ti","Mulán","SuKbG1wC_WI"],
    ["Qué hay más allá","Vaiana (Moana)","TsI7co5OWtg"],
    ["No se habla de Bruno","Encanto","wTi8yLyHeb8"],
    ["En lo profundo","Encanto","7JXVgNvIXcI"],
    ["Dos oruguitas","Encanto","eF2Oha8R71w"],
    ["Mucho más allá","Frozen 2","VxBtzRiWBsY"],
    ["Hazme un muñeco de nieve","Frozen","nD5He6e_iYc"],
    ["I Will Always Love You","El guardaespaldas","3JWTaaS7LdU"],
    ["Shallow","Nace una estrella","DPXHMBKY39M"],
    ["Footloose","Kenny Loggins","HvropLxYb5c"],
    ["Eye of the Tiger","Rocky III","btPJPFnesV4"],
    ["You've Got a Friend in Me","Randy Newman (Toy Story)","1MPZRcyTrcU"],
    ["Friend Like Me","Robin Williams (Aladdín)","pF4OH-6NgFY"],
    ["Be Our Guest","La Bella y la Bestia","npJa14mxCVY"],
    ["Part of Your World","Jodi Benson (La Sirenita)","sg1Y6Vxl6Nk"],
    ["In Summer","Olaf (Frozen)","gfxRz6pSj7s"],
    ["You're Welcome","Dwayne Johnson (Moana)","79DijItQXMM"],
    ["I'm a Believer","Smash Mouth (Shrek)","xCP7bCJxxm8"],
    ["Can You Feel the Love Tonight","Elton John (El Rey León)","KjgWWjkNbhU"],
  ]},
  { id:"fiesta", name:"Fiesta / Para saltar", em:"🎉", songs:[
    ["Aserejé","Las Ketchup","arZZw8NyPq8"],
    ["Macarena","Los del Río","zWaymcVmJ-A"],
    ["La Bomba","King África","WCQuf90qf9U"],
    ["Suavemente","Elvis Crespo","WPiEbYSF9kE"],
    ["Danza Kuduro","Don Omar ft. Lucenzo","BbWY-avjDto"],
    ["Bara Bará Bere Berê","Alex Ferrari","JI9CJuZqawY"],
    ["La Mordidita","Ricky Martin","lBztnahrOFw"],
    ["Sopa de caracol","Banda Blanca","JkQmrPXwSNU"],
    ["El venao","Los Cantantes","b7aYO4PCgSo"],
    ["El baile del gorila","Melody","90avMgG5NAM"],
    ["Tic Tic Tac","Carrapicho","MDAdr9L2H_Q"],
    ["El Tiburón","Proyecto Uno","TkIX26iWTIM"],
    ["Pégate","Ricky Martin","1G2-r-5ZwnY"],
    ["La vida es un carnaval","Celia Cruz","0nBFWzpWXuM"],
    ["Conga","Gloria Estefan","5SXX-pWzOY8"],
    ["La copa de la vida","Ricky Martin","tF_ggG5dY5U"],
    ["La Gozadera","Gente de Zona ft. Marc Anthony","LECvZ1GUweY"],
    ["Bamboleo","Gipsy Kings","RYQC0h-eJ4o"],
    ["Rasputín","Boney M","5Z0dxsFmX7c"],
    ["Y.M.C.A.","Village People","CS9OO0S5w2k"],
    ["Ai Se Eu Te Pego","Michel Teló","hcm55lU9knw"],
    ["Mambo No. 5 (A Little Bit of...)","Lou Bega","n2qgHu7HJLw"],
    ["Mambo","Azúcar Moreno","kqcoKBkRAVI"],
    ["Vamos a la Playa","Righeira","x0OMFm8FO90"],
    ["El Meneaito","Gaby","dgj8oSMxaZI"],
    ["Fiesta","Bomba Estéreo","BPT90x5UzN8"],
    ["Sabes a Chocolate","Kumbia Kings","FxLBrXzqHOI"],
    ["Bailar","Deorro ft. Pitbull & Elvis Crespo","EGBcwAuyLNI"],
    ["Que Viva la Vida","Wisin","Ixf_qyN3yMc"],
  ]},
  { id:"rockes", name:"Rock en Español 🤘", em:"🤟", songs:[
    ["Lamento Boliviano","Enanitos Verdes","hReAuaAuJOE"],
    ["La Ingrata","Café Tacvba","kIr8hsVTCzg"],
    ["Eres","Café Tacvba","98Akpf1ph2o"],
    ["Entre dos tierras","Héroes del Silencio","SzimletXB7M"],
    ["Devuélveme a mi chica","Hombres G","sHQ9BdvZPco"],
    ["Clavado en un bar","Maná","ks0RzQRA79w"],
    ["Mariposa traicionera","Maná","av3wkasS-WQ"],
    ["Vivir sin aire","Maná","g3uxeG1rrlE"],
    ["En el muelle de San Blas","Maná","teprNzF6J1I"],
    ["Labios compartidos","Maná","BSRKbUnCX-w"],
    ["La célula que explota","Caifanes","WXthANus1YM"],
    ["Afuera","Caifanes","UamQYzPCwUg"],
    ["Chilanga banda","Café Tacvba","bKjn26agAEs"],
    ["Maldito duende","Héroes del Silencio","SqB4FSettTI"],
    ["Guitarras blancas","Enanitos Verdes","FIToLaXqCGA"],
    ["Mientes","Camila","5cV5SMnEJ5s"],
    ["Limón y sal","Julieta Venegas","tIpzfs5tBJU"],
    ["Me voy","Julieta Venegas","y8rBC6GCUjg"],
    ["Frijolero","Molotov","8iJMOBcPQyg"],
    ["El duelo","La Ley","nSEz_Bb6GKc"],
    ["Tu cárcel","Enanitos Verdes","BQAKKp6ziD0"],
    ["Labios Rotos","Zoé","rhZixDl6fAE"],
    ["Nada","Zoé ft. Bunbury","jyfyPe8uJEY"],
    ["La Iguana","Fobia","bpjO4i38l9w"],
    ["Mentira","La Ley","d1dcXgGQT2M"],
    ["Gimme Tha Power","Molotov","TXzdHsgQVWo"],
    ["Kumbala","Maldita Vecindad","erp0bg7LrkI"],
    ["Nubes","Caifanes","qgTEBxufPT8"],
    ["La Chispa Adecuada","Héroes del Silencio","mNO5sfXKSmI"],
  ]},
  { id:"urbano", name:"Trap / Urbano", em:"🎤", songs:[
    ["Tití Me Preguntó","Bad Bunny","juRFjpB5Ppg"],
    ["Me Porto Bonito","Bad Bunny ft. Chencho","saGYMhApaH8"],
    ["Quevedo: BZRP #52","Bizarrap","A_g3lMcWVy0"],
    ["Shakira: BZRP #53","Bizarrap","CocEMWdc7Ck"],
    ["Mamichula","Trueno, Nicki Nicole","NUteQQCMa_k"],
    ["Goteo","Duki","AaHixdQS2jA"],
    ["Bandido","Myke Towers","W6fme7tcweQ"],
    ["Vete","Bad Bunny","iB_dfHQhKKc"],
    ["Yonaguni","Bad Bunny","doLMt10ytHY"],
    ["Callaíta","Bad Bunny","acEOASYioGY"],
    ["Con Calma","Daddy Yankee & Snow","GQwj_FRntp8"],
    ["BZRP Music Sessions #50","Duki","Gzs60iBgd3E"],
    ["BZRP Music Sessions #23","Paulo Londra","WkgHkrM9fo0"],
    ["Adán y Eva","Paulo Londra","aSjflT_J0Xo"],
    ["Nena maldición","Paulo Londra","bX3S-_jUauc"],
    ["Loca","Khea ft. Duki & Cazzu","XQ0D_QD_DhM"],
    ["Otro trago","Sech","BeOcp9pCLRU"],
    ["Dance Crip","Trueno","JWRlTezTF2k"],
    ["Además de mí","Rusherking, Tiago PZK","_43VJRhcPOc"],
    ["Una noche en Medellín","Cris Mj","tgB5Iw6rVvM"],
    ["Provenza","Karol G","i9gxO_5vA-Q"],
    ["Bichota","Karol G","QaXhVryxVBk"],
    ["Ella Quiere Beber","Anuel AA","rRRtPognZXI"],
    ["Wapo Traketero","Nicki Nicole","0wLrPWueUJI"],
    ["Nada","Cazzu ft. Lyanno, Rauw Alejandro & Dalex","OU_Mpu56_Qo"],
    ["Normal","Feid","oD5f55ohsc4"],
    ["Todo de Ti","Rauw Alejandro","jDVGSXE0fEA"],
    ["Punto G","Quevedo","z8uyayN3RbE"],
    ["Ella Baila Sola","Eslabón Armado, Peso Pluma","1TVyEcR5pcw"],
    ["Blackout","Emilia, TINI, Nicki Nicole","l0SnyXFAhIw"],
  ]},
  { id:"baladas", name:"Baladas Románticas", em:"💔", songs:[
    ["Amor eterno","Rocío Dúrcal","7XAUNqTOQx8"],
    ["Hasta que te conocí","Juan Gabriel","lDSNXaqNX1E"],
    ["Y cómo es él","José Luis Perales","XBA5J0B2Llg"],
    ["Historia de un amor","Luis Miguel","kqObd2CcEKc"],
    ["El día que me quieras","Luis Miguel","xk0O35bcIFc"],
    ["Bésame mucho","Cesária Évora","tix6y54jSVc"],
    ["Por debajo de la mesa","Luis Miguel","TIuLNA9mcnU"],
    ["La media vuelta","Luis Miguel","zRdbJvKT66w"],
    ["Sabor a mí","Luis Miguel","cNo-d6Y6w8Y"],
    ["Querida","Juan Gabriel","o3J3nrdS2_c"],
    ["Abrázame muy fuerte","Juan Gabriel","Fbi481QFo4Y"],
    ["Se me olvidó otra vez","Juan Gabriel","Xw8nWQOq-XY"],
    ["Contigo en la distancia","Luis Miguel","lLiPh6kmFoU"],
    ["El triste","José José","9z5PU9H-b28"],
    ["Gavilán o paloma","José José","kdE8NHUc0s4"],
    ["La nave del olvido","José José","BprZX_bGhhg"],
    ["Cómo fui a enamorarme de ti","Los Bukis","Nvd9M6bEPEw"],
    ["Acá entre nos","Vicente Fernández","Zy89cMj4W68"],
    ["Volver, volver","Vicente Fernández","NPg_jbGYzgA"],
    ["Sombras nada más","Javier Solís","09bf9dFw_fU"],
    ["Inolvidable","Luis Miguel","Ggxj6aJpRe4"],
    ["Perdóname","Camilo Sesto","603sSTCvBmg"],
    ["Vivir Así Es Morir de Amor","Camilo Sesto","mZzZsg1XtrE"],
    ["Cómo Te Extraño Mi Amor","Leo Dan","-HrpraXeppU"],
    ["Fue Tan Poco Tu Cariño","Rocío Dúrcal","W1Z7kjdupBk"],
    ["Si No Te Hubieras Ido","Marco Antonio Solís","JhrktzDXExs"],
    ["O Me Voy O Te Vas","Marco Antonio Solís","6N2LEajhs30"],
    ["Te Quiero","José Luis Perales","e74D9278gEc"],
    ["Amigo","Roberto Carlos","2turYlqsg-U"],
  ]},
  { id:"folklore", name:"Folklore Argentino 🇦🇷", em:"🪕", songs:[
    ["Zamba de mi esperanza","Los Nocheros","Jdswdh2VoWY"],
    ["Sólo le pido a Dios","León Gieco","x5PJoP9x-Ys"],
    ["Como la cigarra","Mercedes Sosa","ArcS3QeYR8s"],
    ["Alfonsina y el mar","Mercedes Sosa","Ph-EYdzrWWQ"],
    ["Gracias a la vida","Mercedes Sosa","lDFuHhflHsw"],
    ["Cinco siglos igual","León Gieco","5xYY-1plZmQ"],
    ["Merceditas","Los Nocheros","tVfD8qpZwbk"],
    ["El cosechero","Ramona Galarza","-nBVkwWYugs"],
    ["Balderrama","Mercedes Sosa","bXt4yEpgdzo"],
    ["La pomeña","Mercedes Sosa","1_vKWmQ1jgM"],
    ["Canción con todos","Mercedes Sosa","IqxMGNOm4pk"],
    ["Luna tucumana","Atahualpa Yupanqui","70WmQk96Btc"],
    ["Los ejes de mi carreta","Atahualpa Yupanqui","w9g9jvZ4yJ0"],
    ["El arriero","Atahualpa Yupanqui","ezUvnJOvV98"],
    ["Zamba para no morir","Mercedes Sosa","jVZ28nG3HsE"],
    ["Todo cambia","Mercedes Sosa","0khKL3tTOTs"],
    ["Duerme negrito","Mercedes Sosa","LVplt5Dq7IY"],
    ["Entre a mi pago sin golpear","Los Nocheros","njFEfM2bUVk"],
    ["La López Pereyra","Los Chalchaleros","oEvN8LHF-Oo"],
    ["Nostalgias santiagueñas","Los Chalchaleros","K76oIWnnGrg"],
    ["El humahuaqueño","Los Fronterizos","AgDIBOFQsW0"],
    ["Si Se Calla El Cantor","Horacio Guarany","aAuKFZoUF50"],
    ["La Telesita","Los Manseros Santiagueños","0WcF_vET23k"],
    ["Zamba del Pañuelo","Chaqueño Palavecino","ZtFFArYKGbg"],
    ["Puente Pexoa","Canto del Alma","-_faSxVgHHs"],
    ["Quimey Neuquén","José Larralde","j8TMAqg-4Zk"],
    ["El Porqué","José Larralde","AFVxSdde1HI"],
    ["Que Nadie Sepa Mi Sufrir","Soledad","0xdW1qC-2vg"],
    ["La Nochera","Los Chalchaleros","SP0h7ZmjeGQ"],
  ]},
  { id:"infantiles", name:"Infantiles", em:"🧸", songs:[
    ["Manuelita","María Elena Walsh","D4HchTy42_c"],
    ["El Reino del Revés","María Elena Walsh","6wNtrOSvSqg"],
    ["La vaca estudiosa","María Elena Walsh","Mt_GHyfq2wY"],
    ["Canción del jacarandá","María Elena Walsh","qBuV_EzjRCI"],
    ["La reina Batata","María Elena Walsh","5okeTCGhad8"],
    ["En el país de Nomeacuerdo","María Elena Walsh","Re0qOc06ji4"],
    ["Twist del Mono Liso","María Elena Walsh","iVsdJ6SMWlI"],
    ["Canción de tomar el té","María Elena Walsh","Cx1vGU-utT4"],
    ["El pulpo cocinero","Canticuénticos","4g3Zj-rvv4k"],
    ["Cumbia del monstruo","Canticuénticos","TqtL_r-7LAI"],
    ["Va a llover","Canticuénticos","op5XHJdBIwg"],
    ["Chu chu ua","Piñón Fijo","VsDD-AAUwS0"],
    ["Vocales que son cinco","Piñón Fijo","mwMbNsRZS_I"],
    ["Me muevo para aquí","Diego Topa","BBEMtbfvUV8"],
    ["El sapo no se lava el pie","El Payaso Plim Plim","OpBKfxvidyM"],
    ["Ilarié","Xuxa","KxbjOuRJeWc"],
    ["Cumpleaños feliz","Parchís","wGpJ9xv7LwY"],
    ["Hola don Pepito, hola don José","Gaby, Fofó y Miliki","1zaCmh4DwhQ"],
    ["Había una vez un circo","Gaby, Fofó y Miliki","7TxjX3oGI_M"],
    ["La gallina Turuleca","Gaby, Fofó y Miliki","ybF3IVbV1tc"],
    ["La vaca Lola","La Granja de Zenón","4PXoKuXAWFI"],
    ["El pollito pío","Pulcino Pio","57exIXuPdtY"],
    ["Soy una taza","CantaJuego","wXnNJvyYjrM"],
    ["La vecindad del Chavo","El Chavo del 8","0AR-OIbxrUQ"],
    ["Cha-La Head-Cha-La (Dragon Ball Z)","Adrián Barba","cslLhxL61vg"],
    ["Tema de Pokémon (¡Atrápalos ya!)","Pokémon","YlR3FiXp99k"],
    ["Te quiero yo","Barney","V24UKLTQ2HQ"],
    ["Los opuestos","Pim Pau","M49tP6T1eMw"],
    ["Juguemos en el bosque","El Payaso Plim Plim","-sdV9uESOlU"],
    ["Susanita","Miliki","fOOEu9ym90E"],
  ]},
  { id:"popnac", name:"Pop Nacional 🇦🇷", em:"💿", songs:[
    ["Don","Miranda!","32DOcN9A0TQ"],
    ["Yo te diré","Miranda!","AQRFs-JttnM"],
    ["Perfecta","Miranda!","x432t2voAXw"],
    ["Tu misterioso alguien","Miranda!","yfzp3LplRew"],
    ["Ciudad mágica","Tan Biónica","0d_yokJsjCY"],
    ["Beautiful","Tan Biónica","ywyFAmrpKMw"],
    ["Obsesionario en La mayor","Tan Biónica","t-siIWTtTdU"],
    ["La melodía de Dios","Tan Biónica","jgNRKk_MWm0"],
    ["Oncemil","Abel Pintos","NKG-8HY2GVA"],
    ["Sin principio ni final","Abel Pintos","amHpLT0xCzg"],
    ["Motivos","Abel Pintos","x_ZOACDZlYQ"],
    ["Amo","Axel","zSebyN0EZD0"],
    ["Te voy a amar","Axel","KJC3TGwG8jw"],
    ["Como tú","Luciano Pereyra","rlH_d0HZJv0"],
    ["Enséñame a vivir sin ti","Luciano Pereyra","plf48mLqdJs"],
    ["Nada fue un error","Coti ft. Andrés Calamaro","f3odw15MsJI"],
    ["Antes que ver el sol","Coti ft. Dani Martín","3Jhfbvqzhg0"],
    ["Andando","Diego Torres","zLk6rTUZJEs"],
    ["Sueños","Diego Torres","ijy3TmMq6uk"],
    ["Tratar de estar mejor","Diego Torres","v59rGCGtVnw"],
    ["Cambio dolor","Natalia Oreiro","-LjoWL1MxyY"],
    ["Tu veneno","Natalia Oreiro","qtQOnmfSRsY"],
    ["Me muero de amor","Natalia Oreiro","7BzaxvScaMY"],
    ["Guapas","Bandana","fxKZVGY-t3w"],
    ["Llega la noche","Bandana","eJI0nlU9py8"],
    ["Sweet Baby","Erreway","N_gvxYNAawY"],
    ["Vamos al cielo","Erreway","16ZGFo-LBso"],
    ["A bailar","Lali","uWam5F0n10k"],
    ["Mil años luz","Lali","F_XG7-HHWqA"],
    ["Disciplina","Lali","eU6Klg29lC4"],
    ["Cupido","TINI","BjmYyub5J8k"],
    ["Todo a pulmón","Alejandro Lerner","yB557r_ESTU"],
    ["Me das cada día más","Valeria Lynch","QQpV1g2-Qns"],
    ["La fuerza del engaño","Marcela Morelo","j4YHwiIAe8o"],
  ]},
  { id:"boybands", name:"Boy Bands y Pop 2000s", em:"🕺", songs:[
    ["Everybody (Backstreet's Back)","Backstreet Boys","J47YIH1XCGE"],
    ["As Long as You Love Me","Backstreet Boys","m8_t0L_CtVU"],
    ["Larger than Life","Backstreet Boys","pjvQZzkeI_o"],
    ["Bye Bye Bye","*NSYNC","fxHjlCBHuzA"],
    ["It's Gonna Be Me","*NSYNC","dyDBxOiR4dc"],
    ["...Baby One More Time","Britney Spears","ZXhrv3WL4X4"],
    ["Oops!... I Did It Again","Britney Spears","wsHbHR3Os6U"],
    ["Toxic","Britney Spears","tVdr_JWmnsA"],
    ["Wannabe","Spice Girls","tscL_I2v7pU"],
    ["Genie in a Bottle","Christina Aguilera","yz4me7Vwr1w"],
    ["Burnin' Up","Jonas Brothers","SPGMAjkOsLg"],
    ["The Best of Both Worlds","Hannah Montana","pAWseFS4eAk"],
    ["Breaking Free","High School Musical","08NXKsXK7XU"],
    ["We're All in This Together","High School Musical","Bz73c8rz4QA"],
    ["Complicated","Avril Lavigne","DTtb9rt1tnk"],
    ["Girlfriend","Avril Lavigne","g0TiuFwX0r8"],
    ["Sk8er Boi","Avril Lavigne","UYocLBXr7hQ"],
    ["What Makes You Beautiful","One Direction","d57qSDCxVA4"],
    ["Story of My Life","One Direction","8M3Vlnu_i3c"],
    ["Barbie Girl","Aqua","77zog6Up_Yg"],
    ["Party in the U.S.A.","Miley Cyrus","7ARXrfGbQaI"],
    ["Baby","Justin Bieber","GqWYJT-iMTw"],
    ["Hot n Cold","Katy Perry","C-jAPrdc3PI"],
    ["Poker Face","Lady Gaga","oG-4Uvhm4lI"],
    ["I Gotta Feeling","Black Eyed Peas","Wnn6M1nNiKQ"],
    ["Since U Been Gone","Kelly Clarkson","p0BiGek2bKA"],
    ["Umbrella","Rihanna","xXD5tltX9Pg"],
    ["Beautiful Soul","Jesse McCartney","gFP0m8pRtRs"],
    ["Don't Cha","The Pussycat Dolls ft. Busta Rhymes","0IGdk5Xr4vc"],
    ["My Love","Westlife","vKwowKeEv5w"],
    ["Come Clean","Hilary Duff","RDLNmailOwI"],
    ["Say My Name","Destiny's Child","KzMw3Pp0aqg"],
    ["Boom, Boom, Boom, Boom!!","Vengaboys","gM65SDMiXBE"],
  ]},
  { id:"cachengue", name:"Cachengue y RKT", em:"🔊", songs:[
    ["L-Gante: BZRP #38","Bizarrap","b-mUsAXh6wI"],
    ["Malianteo 420","L-Gante","LWXv8qSV4Ow"],
    ["Una foto (Remix)","Mesita, Nicki Nicole, Tiago PZK, Emilia","9C5JPrN5xQY"],
    ["Tamo chelo","El Noba","0sBPRJ5GHuM"],
    ["Butakera","La Joaqui, Alan Gomez, El Noba","iGwJ8TytOAU"],
    ["PICA","El Noba, La Joaqui","dP-5w3vnoaU"],
    ["Pa' la Selección","La T y La M","gCVqd5R5ZwU"],
    ["Amor de vago","La T y La M, Malandro","MDbwr3YtTZc"],
    ["Tu jardín con enanitos","Roze, Max Carra, Valen, Ramky","ZsSi6FHxY8Q"],
    ["Turreo Sessions #5","DJ Tao, Kaleb Di Masi","WXJKabqqxOY"],
    ["Turreo Sessions #7","DJ Tao, El Noba","oQTBi-f3ofw"],
    ["Turreo Sessions #22","DJ Tao, Roze","6nXMYkyl2wM"],
    ["Tirate un paso","Los Wachiturros","9iKe5EwLrDo"],
    ["Bailan rochas y chetas","Nene Malo","ebmes8Ci7_0"],
    ["Amigos con derecho","Nene Malo","ow6kBjytnMI"],
    ["Mi nena Facebook","Los Nota Lokos","TTVaU8fOWc8"],
    ["Wanda Nara","La Joaqui, Martín Vegas","Ccu3QU2Mg6g"],
    ["Te vi","La Joaqui, Callejero Fino","DO0FYwe86D4"],
    ["Saveiro","Perro Primo, La Joaqui, DT.Bilardo","Nh7bb55tZQU"],
    ["¿Y pa la wacha loca?","Gusty DJ, La Joaqui, L-Gante","gnMw8MSmwKs"],
    ["Uno más uno (Remix)","L-Gante, Seba TC, DT.Bilardo","GMYqHRFfNbM"],
    ["Yendo no, llegando","Perro Primo, El Noba","UWXgK-l0bag"],
    ["Dubai","Mesita","aelBPjXExIs"],
    ["Que se mueran los feos","Mala Fama","PSLDJf4wkRM"],
    ["Llegamos los Pibes Chorros","Pibes Chorros","vmMu1pBYUCk"],
    ["Bar","TINI, L-Gante","uWb2EtOFEBM"],
    ["Cumbia piola","El Noba","QLCnTO2Qj-c"],
    ["Hoy juega la Argentina","La T y La M","j0ZgqLeye2I"],
  ]},
  { id:"kpop", name:"K-Pop 🇰🇷", em:"💜", songs:[
    ["Dynamite","BTS","HaEYUJ2aRHs"],
    ["Butter","BTS","NNCBq0JHXsU"],
    ["Boy With Luv","BTS","Q-erYa8cwnc"],
    ["DNA","BTS","IfemyZEhfpY"],
    ["Fake Love","BTS","NT8ePWlgx_Y"],
    ["DDU-DU DDU-DU","BLACKPINK","IPzouyj7FLA"],
    ["How You Like That","BLACKPINK","8mA6jIeojnk"],
    ["Kill This Love","BLACKPINK","z7e54L8usac"],
    ["Pink Venom","BLACKPINK","4N15045PHEA"],
    ["Gangnam Style","PSY","4AgDYTuZWOw"],
    ["Fantastic Baby","BIGBANG","oM4KBLQRCM8"],
    ["Gee","Girls' Generation","qizghQs4K6E"],
    ["TT","TWICE","___h2czNhe0"],
    ["Fancy","TWICE","j4OrZV_GAsI"],
    ["Love Shot","EXO","KmRqHwJrTKQ"],
    ["God's Menu","Stray Kids","GyCAzYm1zvk"],
    ["MANIAC","Stray Kids","VG4lpTHuytc"],
    ["Hype Boy","NewJeans","ghrlZIMDzbM"],
    ["Super Shy","NewJeans","0c7zGU2C2mM"],
    ["Red Flavor","Red Velvet","BLavT7w4R9I"],
    ["Psycho","Red Velvet","PyyT5tHbOLw"],
    ["Next Level","aespa","tkzYyEp4zB4"],
    ["Supernova","aespa","LCIs3JXb5Aw"],
    ["Dalla Dalla","ITZY","miqQAzOXPBo"],
    ["Love Dive","IVE","hh5GKVa8VtM"],
    ["Antifragile","LE SSERAFIM","SZiwpL62to8"],
    ["Tomboy","(G)I-DLE","aFoqCI75WoY"],
    ["Seven","Jungkook ft. Latto","Vs64cZbeY88"],
    ["APT.","ROSÉ, Bruno Mars","DiTd771WumE"],
    ["Money","LISA","4YSHPGn9-LM"],
    ["Very Nice","SEVENTEEN","s3CjsNjiKyc"],
    ["Like Crazy","Jimin","5lpppPsc2n4"],
  ]},
];
