// Playlists precargadas. Cada canción = [título, artista, idYouTube].
export const GENRES = [
  { id:"rock", name:"Rock Nacional 🇦🇷", em:"🎸", songs:[
    ["De música ligera","Soda Stereo","T_FkEw27XJ0"],
    ["Persiana americana","Soda Stereo","LalPz4lIZYk"],
    ["En la ciudad de la furia","Soda Stereo","AVEDgT_lG60"],
    ["Cuando pase el temblor","Soda Stereo","ZNzYr4U7Zs8"],
    ["Crimen","Gustavo Cerati","uLIs0j2WnlM"],
    ["Seminare","Serú Girán","xVdtGR_zgdA"],
    ["El amor después del amor","Fito Páez","knvgOdKPaMQ"],
    ["Mariposa Technicolor","Fito Páez","CRBincBc_8k"],
    ["Los dinosaurios","Charly García","BAuqozi64WQ"],
    ["Rasguña las piedras","Sui Generis","DrKRNJGAyHw"],
    ["Matador","Los Fabulosos Cadillacs","pjPA7CXutDw"],
    ["Ji Ji Ji","Los Redondos","CnJqYsSOgfg"],
    ["Flaca","Andrés Calamaro","UCF9oHXhDMU"],
    ["Yo vengo a ofrecer mi corazón","Fito Páez","cg1FigbX6BM"],
    ["Zona de promesas","Gustavo Cerati","lvCL5EE4bsA"],
    ["Un vestido y un amor","Fito Páez","zwtTWFwO13I"],
    ["Prófugos","Soda Stereo","lGptyREttJ4"],
    ["Trátame suavemente","Soda Stereo","UPVfQKUHTSc"],
    ["Nada personal","Soda Stereo","ko24BZXdK8c"],
    ["Demoliendo hoteles","Charly García","Mm3IgrVsu24"],
    ["No voy en tren","Charly García","P3L10KNMptw"],
    ["Muchacha (ojos de papel)","Almendra","lP7_qMRIXTg"],
    ["La balsa","Los Gatos","_I9aI8ejnqY"],
    ["Cactus","Gustavo Cerati","a7_al3uciVc"],
    ["La argentinidad al palo","Bersuit Vergarabat","972s6-BLGtQ"],
    ["Se viene","Bersuit Vergarabat","ACRVZzKu5h0"],
    ["Loco (tu forma de ser)","Los Auténticos Decadentes","fgXDHQm5eq4"],
    ["La rubia tarada","Sumo","QuaGBNkdTso"],
  ]},
  { id:"cumbia", name:"Cumbia y Cuarteto 🇦🇷", em:"🪗", songs:[
    ["Soy cordobés","Rodrigo","EZaO0mgpy6I"],
    ["La mano de Dios","Rodrigo","EAk-l1VHzBw"],
    ["Ocho cuarenta","Rodrigo","3QKR5RxSV1E"],
    ["Quién se ha tomado todo el vino","La Mona Jiménez","YjIhq5dJKQA"],
    ["No me arrepiento de este amor","Gilda","8iUkmnLc1ec"],
    ["Fuiste","Gilda","mm_SwD5PYvY"],
    ["Corazón valiente","Gilda","yykYZhD4Wwc"],
    ["No te creas tan importante","Damas Gratis","j6CUfl4aX9s"],
    ["El bombón asesino","Los Palmeras","UeFC_9oGqWg"],
    ["La pollera amarilla","Los Palmeras","W9sQmwS6c4Q"],
    ["La ventanita","Grupo Sombras","Ykt2edUBEyA"],
    ["Beso a beso","La Mona Jiménez","Xv2vXP7R-KI"],
    ["Amor clasificado","Rodrigo","Wp75WKhWT48"],
    ["Cómo olvidarla","Rodrigo","59n6vkmpazE"],
    ["Laura, se te ve la tanga","Damas Gratis","jKgCg4cAVcw"],
    ["Se me ha perdido el corazón","Gilda","X72XPwSKcJ4"],
    ["Paisaje","Gilda","e-uNMZ1wfR4"],
    ["No es mi despedida","Gilda","y4Rtfp0Nx4k"],
    ["La Suavecita","Los Palmeras ft. Soledad","wA6S57yVqA8"],
    ["Nunca me faltes","Antonio Ríos","Du1UJyRwmts"],
    ["Hazme entender","Ráfaga","kDxp-aeJ0sw"],
    ["Mentirosa","Ráfaga","ihrUZRxgef4"],
    ["La Vecina","Amar Azul","wk-nCzxthAo"],
    ["Perdiste","Ulises Bueno","zxgMngLW65E"],
    ["Nunca es suficiente","Los Ángeles Azules","k76BgIb89-s"],
    ["Cómo te voy a olvidar","Los Ángeles Azules","nxXvOEPsE0s"],
  ]},
  { id:"pop", name:"Pop Latino / Reggaetón", em:"🔥", songs:[
    ["Despacito","Luis Fonsi ft. Daddy Yankee","kJQP7kiw5Fk"],
    ["Gasolina","Daddy Yankee","CCF1_jI8Prk"],
    ["Vivir mi vida","Marc Anthony","YXnjy5YlDwk"],
    ["Bailando","Enrique Iglesias","NUsoVlDFqZg"],
    ["La camisa negra","Juanes","kRt2sRyup6A"],
    ["Tusa","Karol G ft. Nicki Minaj","tbneQDc2H3I"],
    ["Hawái","Maluma","pK060iUFWXg"],
    ["Con altura","Rosalía y J Balvin","p7bfOZek9t4"],
    ["La tortura","Shakira ft. Alejandro Sanz","Dsp_8Lm1eSk"],
    ["Hips Don't Lie","Shakira","DUT5rEU6pqM"],
    ["Livin' la Vida Loca","Ricky Martin","p47fEXGabaY"],
    ["Vente Pa' Ca","Ricky Martin ft. Maluma","iOe6dI2JhgU"],
    ["Propuesta indecente","Romeo Santos","QFs3PIZb3js"],
    ["Obsesión","Aventura","8_QY5gFQUTg"],
    ["Felices los 4","Maluma","t_jHrUE5IOk"],
    ["Chantaje","Shakira ft. Maluma","6Mgqbai3fKo"],
    ["El perdón","Nicky Jam & Enrique Iglesias","hXI8RQYC36Q"],
    ["Hasta el amanecer","Nicky Jam","kkx-7fsiWgg"],
    ["Mi Gente","J Balvin","wnJ6LuUFpMo"],
    ["Ginza","J Balvin","zZjSX01P5dE"],
    ["Ay vamos","J Balvin","TapXs54Ah3E"],
    ["China","Anuel, Daddy Yankee, Karol G, Ozuna, J Balvin","0VR3dfZf9Yg"],
    ["Baila Baila Baila","Ozuna","32F2d-wj4Xw"],
    ["Taki Taki","DJ Snake, Ozuna, Cardi B, Selena","ixkoVwKQaJg"],
    ["Corazón","Maluma ft. Nego do Borel","GmHrjFIWl6U"],
    ["Reggaetón Lento","CNCO","7jpqqBX-Myw"],
    ["Súbeme la radio","Enrique Iglesias","9sg-A-eS6Ig"],
  ]},
  { id:"inter", name:"Rock & Pop Internacional 🌎", em:"🌎", songs:[
    ["Bohemian Rhapsody","Queen","fJ9rUzIMcZQ"],
    ["Don't Stop Me Now","Queen","HgzGwKwLmgM"],
    ["Sweet Child O' Mine","Guns N' Roses","1w7OgIMMRc4"],
    ["Wonderwall","Oasis","bx1Bh8ZvH84"],
    ["Billie Jean","Michael Jackson","Zi_XLOBDo_Y"],
    ["Someone Like You","Adele","hLQl3WQQoQ0"],
    ["Shape of You","Ed Sheeran","JGwWNGJdvx8"],
    ["Yellow","Coldplay","yKNxeF4KMsY"],
    ["Zombie","The Cranberries","6Ejga4kJUts"],
    ["Smells Like Teen Spirit","Nirvana","hTWKbfoikeg"],
    ["Livin' on a Prayer","Bon Jovi","lDK9QqIzhwk"],
    ["I Want It That Way","Backstreet Boys","4fndeDfaWCg"],
    ["Africa","Toto","FTQbiNvZqaY"],
    ["Believer","Imagine Dragons","7wtfhZwyrcc"],
    ["Rolling in the Deep","Adele","rYEDA3JcQqw"],
    ["We Will Rock You","Queen","-tJYN-eG1zk"],
    ["We Are the Champions","Queen","04854XqcfCY"],
    ["Hey Jude","The Beatles","A_MjCqQoLLA"],
    ["Let It Be","The Beatles","CGj85pVzRJs"],
    ["Imagine","John Lennon","VOgFZfRVaww"],
    ["Hotel California","Eagles","dLl4PZtxia8"],
    ["Every Breath You Take","The Police","OMOGaugKpzs"],
    ["Losing My Religion","R.E.M.","xwtdhWltSIg"],
    ["With or Without You","U2","ujNeHIo7oTE"],
    ["Nothing Else Matters","Metallica","tAGnKpE4NCI"],
    ["Highway to Hell","AC/DC","l482T0yNkeo"],
    ["Thunderstruck","AC/DC","v2AC41dglnM"],
    ["Creep","Radiohead","XFkzRNyygfk"],
    ["Numb","Linkin Park","kXYiU_JCYtU"],
  ]},
  { id:"clasicos", name:"Clásicos 80s / 90s", em:"📼", songs:[
    ["Color esperanza","Diego Torres","Nb1VOQRs-Vs"],
    ["Corazón espinado","Maná ft. Santana","t6omUxqhG78"],
    ["Rayando el sol","Maná","8lbsQyMhMT8"],
    ["Oye mi amor","Maná","h0p8yTqj8i4"],
    ["La incondicional","Luis Miguel","wOjzo02Tmck"],
    ["Ahora te puedes marchar","Luis Miguel","yG7MPEQm1-w"],
    ["La bilirrubina","Juan Luis Guerra","K8PpV3yK5iA"],
    ["A Dios le pido","Juanes","kMIaYXxLnUA"],
    ["Entra en mi vida","Sin Bandera","-hoZpSoKAYE"],
    ["A puro dolor","Son by Four","kAKVT1HWNsg"],
    ["Vivo por ella","Andrea Bocelli & Marta Sánchez","m5UcZ9thgPI"],
    ["Bachata rosa","Juan Luis Guerra","WfMO_AETgB0"],
    ["Burbujas de amor","Juan Luis Guerra","v0ckuv1xBm0"],
    ["Ojalá que llueva café","Juan Luis Guerra","suQC8d-YkeU"],
    ["La flaca","Jarabe de Palo","r2g0pM3PMNQ"],
    ["Corazón partío","Alejandro Sanz","ZMUqIoDtSwc"],
    ["Amiga mía","Alejandro Sanz","44Qh0p9xE6o"],
    ["Mujer contra mujer","Mecano","wVSA2CEIQ7U"],
    ["Hijo de la luna","Mecano","OwGG5fX7bxY"],
    ["Me cuesta tanto olvidarte","Mecano","8f2Vyb014D0"],
    ["La chica de ayer","Nacha Pop","oAcwJlNdwso"],
    ["Eres tú","Mocedades","A5vaIjBQnmk"],
    ["Un beso y una flor","Nino Bravo","d65A4aD2hmg"],
    ["Bidi Bidi Bom Bom","Selena","RKGbjJarMeA"],
    ["Amor prohibido","Selena","dvfZ95ueOcQ"],
  ]},
  { id:"disney", name:"Disney y Películas", em:"🏰", songs:[
    ["Un mundo ideal","Aladdín","2tKPGsm_5-Y"],
    ["Libre soy","Frozen","rVjI9YRc4pE"],
    ["Recuérdame","Coco","rSWj__OmHis"],
    ["Un poco loco","Coco","yZ7cBunq8xo"],
    ["Bajo el mar","La Sirenita","DDSerADikPg"],
    ["My Heart Will Go On","Titanic","9bFHsd3o1w0"],
    ["Colores en el viento","Pocahontas","Tf42lskNSqs"],
    ["Hakuna Matata","El Rey León","qqBqAn3fJ2E"],
    ["Mi reflejo","Mulán","_yTsNxhGE30"],
    ["Cuando empezaré a vivir","Enredados","NjkAgGwXaSs"],
    ["Bella y Bestia son","La Bella y la Bestia","kY7mwb3EhbM"],
    ["El ciclo sin fin","El Rey León","8cZJ_wPpBJg"],
    ["Yo quisiera ya ser el rey","El Rey León","scZAnwaSIlw"],
    ["Veo en ti la luz","Enredados","fZSZMp32XaA"],
    ["No hablaré de mi amor","Hércules","uJcl-pnTB7A"],
    ["Voy a hacer todo un hombre de ti","Mulán","SuKbG1wC_WI"],
    ["Qué hay más allá","Vaiana (Moana)","TsI7co5OWtg"],
    ["No se habla de Bruno","Encanto","wTi8yLyHeb8"],
    ["En lo profundo","Encanto","7JXVgNvIXcI"],
    ["Dos oruguitas","Encanto","DUGtyj5QlEM"],
    ["Mucho más allá","Frozen 2","VxBtzRiWBsY"],
    ["Hazme un muñeco de nieve","Frozen","nD5He6e_iYc"],
    ["I Will Always Love You","El guardaespaldas","3JWTaaS7LdU"],
    ["Shallow","Nace una estrella","JPJjwHAIny4"],
    ["Footloose","Kenny Loggins","ltrMfT4Qz5Y"],
    ["Eye of the Tiger","Rocky III","btPJPFnesV4"],
  ]},
  { id:"fiesta", name:"Fiesta / Para saltar", em:"🎉", songs:[
    ["Aserejé","Las Ketchup","arZZw8NyPq8"],
    ["Macarena","Los del Río","zWaymcVmJ-A"],
    ["La Bomba","King África","WCQuf90qf9U"],
    ["Suavemente","Elvis Crespo","WPiEbYSF9kE"],
    ["Danza Kuduro","Don Omar ft. Lucenzo","7zp1TbLFPp8"],
    ["Bara Bará Bere Berê","Alex Ferrari","sxF9PGRiabw"],
    ["La Mordidita","Ricky Martin","lBztnahrOFw"],
    ["Sopa de caracol","Banda Blanca","JkQmrPXwSNU"],
    ["El venao","Los Cantantes","Iw-GwOdMVes"],
    ["El baile del gorila","Melody","90avMgG5NAM"],
    ["Tic Tic Tac","Carrapicho","MDAdr9L2H_Q"],
    ["El Tiburón","Proyecto Uno","4Qy0vs80T5M"],
    ["Pégate","Ricky Martin","1G2-r-5ZwnY"],
    ["La vida es un carnaval","Celia Cruz","0nBFWzpWXuM"],
    ["Conga","Gloria Estefan","54ItEmCnP80"],
    ["La copa de la vida","Ricky Martin","tF_ggG5dY5U"],
    ["La Gozadera","Gente de Zona ft. Marc Anthony","VMp55KH_3wo"],
    ["Bamboleo","Gipsy Kings","7qbEt_lSib4"],
    ["Rasputín","Boney M","16y1AkoZkmQ"],
    ["Y.M.C.A.","Village People","CS9OO0S5w2k"],
    ["Ai Se Eu Te Pego","Michel Teló","hcm55lU9knw"],
  ]},
  { id:"rockes", name:"Rock en Español 🤘", em:"🤟", songs:[
    ["Lamento Boliviano","Enanitos Verdes","hReAuaAuJOE"],
    ["La Ingrata","Café Tacvba","kIr8hsVTCzg"],
    ["Eres","Café Tacvba","98Akpf1ph2o"],
    ["Entre dos tierras","Héroes del Silencio","SzimletXB7M"],
    ["Devuélveme a mi chica","Hombres G","sHQ9BdvZPco"],
    ["Clavado en un bar","Maná","fBrX8ym3dBM"],
    ["Mariposa traicionera","Maná","av3wkasS-WQ"],
    ["Vivir sin aire","Maná","g3uxeG1rrlE"],
    ["En el muelle de San Blas","Maná","teprNzF6J1I"],
    ["Labios compartidos","Maná","1IgOZaQqB58"],
    ["La célula que explota","Caifanes","LltlG9sU6zg"],
    ["Afuera","Caifanes","gBt1jOtKz6Y"],
    ["Chilanga banda","Café Tacvba","bKjn26agAEs"],
    ["Maldito duende","Héroes del Silencio","SqB4FSettTI"],
    ["Guitarras blancas","Enanitos Verdes","FIToLaXqCGA"],
    ["Mientes","Camila","xftFxCYQTdk"],
    ["Limón y sal","Julieta Venegas","tIpzfs5tBJU"],
    ["Me voy","Julieta Venegas","y8rBC6GCUjg"],
    ["Frijolero","Molotov","8iJMOBcPQyg"],
    ["El duelo","La Ley","gN3YYSuasMk"],
    ["Tu cárcel","Enanitos Verdes","BQAKKp6ziD0"],
  ]},
  { id:"urbano", name:"Trap / Urbano", em:"🎤", songs:[
    ["Tití Me Preguntó","Bad Bunny","Cr8K88UcO0s"],
    ["Me Porto Bonito","Bad Bunny ft. Chencho","saGYMhApaH8"],
    ["Quevedo: BZRP #52","Bizarrap","A_g3lMcWVy0"],
    ["Shakira: BZRP #53","Bizarrap","CocEMWdc7Ck"],
    ["Mamichula","Trueno, Nicki Nicole","NUteQQCMa_k"],
    ["Goteo","Duki","FRthkpJ_NFo"],
    ["Bandido","Myke Towers","W6fme7tcweQ"],
    ["Vete","Bad Bunny","f5aDUB1NCnk"],
    ["Yonaguni","Bad Bunny","doLMt10ytHY"],
    ["Callaíta","Bad Bunny","acEOASYioGY"],
    ["Con Calma","Daddy Yankee & Snow","DiItGE3eAyQ"],
    ["BZRP Music Sessions #50","Duki","Gzs60iBgd3E"],
    ["BZRP Music Sessions #23","Paulo Londra","WkgHkrM9fo0"],
    ["Adán y Eva","Paulo Londra","aSjflT_J0Xo"],
    ["Nena maldición","Paulo Londra","bX3S-_jUauc"],
    ["Loca","Khea ft. Duki & Cazzu","XQ0D_QD_DhM"],
    ["Otro trago","Sech","t_qn-f7XfJo"],
    ["Dance Crip","Trueno","JWRlTezTF2k"],
    ["Además de mí","Rusherking, Tiago PZK","_43VJRhcPOc"],
    ["Una noche en Medellín","Cris Mj","EaIh7tRqdqM"],
    ["Provenza","Karol G","ca48oMV59LU"],
    ["Bichota","Karol G","QaXhVryxVBk"],
  ]},
  { id:"baladas", name:"Baladas Románticas", em:"💔", songs:[
    ["Amor eterno","Rocío Dúrcal","7XAUNqTOQx8"],
    ["Hasta que te conocí","Juan Gabriel","ga5Bo4YdgH4"],
    ["Y cómo es él","José Luis Perales","XBA5J0B2Llg"],
    ["Historia de un amor","Luis Miguel","kqObd2CcEKc"],
    ["El día que me quieras","Luis Miguel","xk0O35bcIFc"],
    ["Bésame mucho","Cesária Évora","tix6y54jSVc"],
    ["Por debajo de la mesa","Luis Miguel","giAE7Yz7gHI"],
    ["La media vuelta","Luis Miguel","VMJnlN8OkgI"],
    ["Sabor a mí","Luis Miguel","cNo-d6Y6w8Y"],
    ["Querida","Juan Gabriel","AQOJ4qF0alk"],
    ["Abrázame muy fuerte","Juan Gabriel","_tNVEhSelH0"],
    ["Se me olvidó otra vez","Juan Gabriel","g5rsnxJWNkM"],
    ["Contigo en la distancia","Luis Miguel","lLiPh6kmFoU"],
    ["El triste","José José","E20G25SCAEg"],
    ["Gavilán o paloma","José José","kdE8NHUc0s4"],
    ["La nave del olvido","José José","BprZX_bGhhg"],
    ["Cómo fui a enamorarme de ti","Los Bukis","Nvd9M6bEPEw"],
    ["Acá entre nos","Vicente Fernández","Zy89cMj4W68"],
    ["Volver, volver","Vicente Fernández","NPg_jbGYzgA"],
    ["Sombras nada más","Javier Solís","UasiMOoMz1o"],
    ["Inolvidable","Luis Miguel","Ggxj6aJpRe4"],
  ]},
  { id:"folklore", name:"Folklore Argentino 🇦🇷", em:"🪕", songs:[
    ["Zamba de mi esperanza","Los Nocheros","Jdswdh2VoWY"],
    ["Sólo le pido a Dios","León Gieco","x5PJoP9x-Ys"],
    ["Como la cigarra","Mercedes Sosa","ArcS3QeYR8s"],
    ["Alfonsina y el mar","Mercedes Sosa","F_FRa9htNiw"],
    ["Gracias a la vida","Mercedes Sosa","lDFuHhflHsw"],
    ["Cinco siglos igual","León Gieco","5xYY-1plZmQ"],
    ["Merceditas","Los Nocheros","tVfD8qpZwbk"],
    ["El cosechero","Ramona Galarza","-nBVkwWYugs"],
    ["Balderrama","Mercedes Sosa","bXt4yEpgdzo"],
    ["La pomeña","Mercedes Sosa","1_vKWmQ1jgM"],
    ["Canción con todos","Mercedes Sosa","IqxMGNOm4pk"],
    ["Luna tucumana","Atahualpa Yupanqui","70WmQk96Btc"],
    ["Los ejes de mi carreta","Atahualpa Yupanqui","w9g9jvZ4yJ0"],
    ["El arriero","Atahualpa Yupanqui","JDJOXVBN-Rk"],
    ["Zamba para no morir","Mercedes Sosa","jVZ28nG3HsE"],
    ["Todo cambia","Mercedes Sosa","0khKL3tTOTs"],
    ["Duerme negrito","Mercedes Sosa","LVplt5Dq7IY"],
    ["Entre a mi pago sin golpear","Los Nocheros","njFEfM2bUVk"],
    ["La López Pereyra","Los Chalchaleros","oEvN8LHF-Oo"],
    ["Nostalgias santiagueñas","Los Chalchaleros","K76oIWnnGrg"],
    ["El humahuaqueño","Los Fronterizos","AgDIBOFQsW0"],
  ]},
];
