// Playlists precargadas. Cada canción = [título, artista, idYouTube].
export const GENRES = [
  { id:"rock", name:"Rock Nacional 🇦🇷", em:"🎸", songs:[
    ["De música ligera","Soda Stereo","T_FkEw27XJ0"],
    ["Persiana americana","Soda Stereo","LalPz4lIZYk"],
    ["En la ciudad de la furia","Soda Stereo","AVEDgT_lG60"],
    ["Cuando pase el temblor","Soda Stereo","ZNzYr4U7Zs8"],
    ["Crimen","Gustavo Cerati","uLIs0j2WnlM"],
    ["Seminare","Serú Girán","xVdtGR_zgdA"],
    ["El amor después del amor","Fito Páez","knvgOdKPaMQ"],
    ["Mariposa Technicolor","Fito Páez","CRBincBc_8k"],
    ["Los dinosaurios","Charly García","BAuqozi64WQ"],
    ["Rasguña las piedras","Sui Generis","DrKRNJGAyHw"],
    ["Matador","Los Fabulosos Cadillacs","pjPA7CXutDw"],
    ["Ji Ji Ji","Los Redondos","CnJqYsSOgfg"],
    ["Flaca","Andrés Calamaro","UCF9oHXhDMU"],
  ]},
  { id:"cumbia", name:"Cumbia y Cuarteto 🇦🇷", em:"🪗", songs:[
    ["Soy cordobés","Rodrigo","EZaO0mgpy6I"],
    ["La mano de Dios","Rodrigo","EAk-l1VHzBw"],
    ["Ocho cuarenta","Rodrigo","3QKR5RxSV1E"],
    ["Quién se ha tomado todo el vino","La Mona Jiménez","YjIhq5dJKQA"],
    ["No me arrepiento de este amor","Gilda","8iUkmnLc1ec"],
    ["Fuiste","Gilda","mm_SwD5PYvY"],
    ["Corazón valiente","Gilda","yykYZhD4Wwc"],
    ["No te creas tan importante","Damas Gratis","j6CUfl4aX9s"],
    ["El bombón asesino","Los Palmeras","UeFC_9oGqWg"],
    ["La pollera amarilla","Los Palmeras","W9sQmwS6c4Q"],
    ["La ventanita","Grupo Sombras","Ykt2edUBEyA"],
  ]},
  { id:"pop", name:"Pop Latino / Reggaetón", em:"🔥", songs:[
    ["Despacito","Luis Fonsi ft. Daddy Yankee","kJQP7kiw5Fk"],
    ["Gasolina","Daddy Yankee","CCF1_jI8Prk"],
    ["Vivir mi vida","Marc Anthony","YXnjy5YlDwk"],
    ["Bailando","Enrique Iglesias","NUsoVlDFqZg"],
    ["La camisa negra","Juanes","kRt2sRyup6A"],
    ["Tusa","Karol G ft. Nicki Minaj","tbneQDc2H3I"],
    ["Hawái","Maluma","pK060iUFWXg"],
    ["Con altura","Rosalía y J Balvin","p7bfOZek9t4"],
    ["La tortura","Shakira ft. Alejandro Sanz","Dsp_8Lm1eSk"],
    ["Hips Don't Lie","Shakira","DUT5rEU6pqM"],
    ["Livin' la Vida Loca","Ricky Martin","p47fEXGabaY"],
    ["Vente Pa' Ca","Ricky Martin ft. Maluma","iOe6dI2JhgU"],
  ]},
  { id:"inter", name:"Rock & Pop Internacional 🌎", em:"🌎", songs:[
    ["Bohemian Rhapsody","Queen","fJ9rUzIMcZQ"],
    ["Don't Stop Me Now","Queen","HgzGwKwLmgM"],
    ["Sweet Child O' Mine","Guns N' Roses","1w7OgIMMRc4"],
    ["Wonderwall","Oasis","bx1Bh8ZvH84"],
    ["Billie Jean","Michael Jackson","Zi_XLOBDo_Y"],
    ["Someone Like You","Adele","hLQl3WQQoQ0"],
    ["Shape of You","Ed Sheeran","JGwWNGJdvx8"],
    ["Yellow","Coldplay","yKNxeF4KMsY"],
    ["Zombie","The Cranberries","6Ejga4kJUts"],
    ["Smells Like Teen Spirit","Nirvana","hTWKbfoikeg"],
    ["Livin' on a Prayer","Bon Jovi","lDK9QqIzhwk"],
    ["I Want It That Way","Backstreet Boys","4fndeDfaWCg"],
    ["Africa","Toto","FTQbiNvZqaY"],
    ["Believer","Imagine Dragons","7wtfhZwyrcc"],
  ]},
  { id:"clasicos", name:"Clásicos 80s / 90s", em:"📼", songs:[
    ["Color esperanza","Diego Torres","Nb1VOQRs-Vs"],
    ["Corazón espinado","Maná ft. Santana","t6omUxqhG78"],
    ["Rayando el sol","Maná","8lbsQyMhMT8"],
    ["Oye mi amor","Maná","h0p8yTqj8i4"],
    ["La incondicional","Luis Miguel","wOjzo02Tmck"],
    ["Ahora te puedes marchar","Luis Miguel","yG7MPEQm1-w"],
    ["La bilirrubina","Juan Luis Guerra","K8PpV3yK5iA"],
    ["A Dios le pido","Juanes","kMIaYXxLnUA"],
    ["Entra en mi vida","Sin Bandera","-hoZpSoKAYE"],
    ["A puro dolor","Son by Four","kAKVT1HWNsg"],
  ]},
  { id:"disney", name:"Disney y Películas", em:"🏰", songs:[
    ["Un mundo ideal","Aladdín","2tKPGsm_5-Y"],
    ["Libre soy","Frozen","rVjI9YRc4pE"],
    ["Recuérdame","Coco","rSWj__OmHis"],
    ["Un poco loco","Coco","yZ7cBunq8xo"],
    ["Bajo el mar","La Sirenita","DDSerADikPg"],
    ["My Heart Will Go On","Titanic","9bFHsd3o1w0"],
    ["Colores en el viento","Pocahontas","Tf42lskNSqs"],
    ["Hakuna Matata","El Rey León","qqBqAn3fJ2E"],
    ["Mi reflejo","Mulán","_yTsNxhGE30"],
    ["Cuando empezaré a vivir","Enredados","NjkAgGwXaSs"],
    ["Bella y Bestia son","La Bella y la Bestia","kY7mwb3EhbM"],
  ]},
  { id:"fiesta", name:"Fiesta / Para saltar", em:"🎉", songs:[
    ["Aserejé","Las Ketchup","arZZw8NyPq8"],
    ["Macarena","Los del Río","zWaymcVmJ-A"],
    ["La Bomba","King África","WCQuf90qf9U"],
    ["Suavemente","Elvis Crespo","WPiEbYSF9kE"],
    ["Danza Kuduro","Don Omar ft. Lucenzo","7zp1TbLFPp8"],
    ["Bara Bará Bere Berê","Alex Ferrari","sxF9PGRiabw"],
  ]},
  { id:"rockes", name:"Rock en Español 🤘", em:"🤟", songs:[
    ["Lamento Boliviano","Enanitos Verdes","hReAuaAuJOE"],
    ["La Ingrata","Café Tacvba","kIr8hsVTCzg"],
    ["Eres","Café Tacvba","98Akpf1ph2o"],
    ["Entre dos tierras","Héroes del Silencio","SzimletXB7M"],
    ["Devuélveme a mi chica","Hombres G","sHQ9BdvZPco"],
    ["Clavado en un bar","Maná","fBrX8ym3dBM"],
  ]},
  { id:"urbano", name:"Trap / Urbano", em:"🎤", songs:[
    ["Tití Me Preguntó","Bad Bunny","Cr8K88UcO0s"],
    ["Me Porto Bonito","Bad Bunny ft. Chencho","saGYMhApaH8"],
    ["Quevedo: BZRP #52","Bizarrap","A_g3lMcWVy0"],
    ["Shakira: BZRP #53","Bizarrap","CocEMWdc7Ck"],
    ["Mamichula","Trueno, Nicki Nicole","NUteQQCMa_k"],
    ["Goteo","Duki","FRthkpJ_NFo"],
    ["Bandido","Myke Towers","W6fme7tcweQ"],
  ]},
  { id:"baladas", name:"Baladas Románticas", em:"💔", songs:[
    ["Amor eterno","Rocío Dúrcal","7XAUNqTOQx8"],
    ["Hasta que te conocí","Juan Gabriel","ga5Bo4YdgH4"],
    ["Y cómo es él","José Luis Perales","XBA5J0B2Llg"],
    ["Historia de un amor","Luis Miguel","kqObd2CcEKc"],
    ["El día que me quieras","Luis Miguel","xk0O35bcIFc"],
    ["Bésame mucho","Cesária Évora","tix6y54jSVc"],
  ]},
  { id:"folklore", name:"Folklore Argentino 🇦🇷", em:"🪕", songs:[
    ["Zamba de mi esperanza","Los Nocheros","Jdswdh2VoWY"],
    ["Sólo le pido a Dios","León Gieco","x5PJoP9x-Ys"],
    ["Como la cigarra","Mercedes Sosa","ArcS3QeYR8s"],
    ["Alfonsina y el mar","Mercedes Sosa","F_FRa9htNiw"],
    ["Gracias a la vida","Mercedes Sosa","lDFuHhflHsw"],
    ["Cinco siglos igual","León Gieco","5xYY-1plZmQ"],
  ]},
];
